name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        include:
          - os: macOS-latest
            target: x86_64-apple-darwin
            binary_suffix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_suffix: ".exe"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Generate embedded roles
        run: deno task generate

      - name: Build binary
        run: |
          deno compile --allow-env --target ${{ matrix.target }} -o mcp-roles${{ matrix.binary_suffix }} main.ts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcp-roles-${{ matrix.target }}
          path: mcp-roles${{ matrix.binary_suffix }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mcp-roles-x86_64-apple-darwin/mcp-roles
            mcp-roles-x86_64-pc-windows-msvc/mcp-roles.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
